application: megapix
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

#RESOURCE HANDLERS(BELOW):
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /resources
  static_dir: resources

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

#URL HANDLERS (BELOW):
- url: /.*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
- name: requests
  version: latest
